name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["7.4", "8.0", "8.1"]
    name: PHP ${{ matrix.php-versions }} test
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@master
        with:
          php_version: ${{ matrix.php-versions }}
      - name: PHPUnit Tests
        uses: php-actions/phpunit@17-php-versions
        with:
          bootstrap: vendor/autoload.php
          configuration: tests/phpunit.xml
          args: --coverage-text
